name: Veracode SCA Scan
#
on: 
  push:
    paths-ignore:
      - "README.md"
  schedule:
    - cron: 15 14 * * 6

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Set up python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install pipenv
        run: |
          pip install pipenv
          pipenv install -r requirements.txt
#      - name: Install requirements
#        run: pip install -r requirements.txt
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
         curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --allow-dirty
#         curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --debug --skip-collectors pipenv
#        uses: Lerer/veracode-sca@v1.0.1 
#        uses: lerer/veracode-sca@fix-execSync-buffer-overflow
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          quick: true
#          create-issues: true 
#          fail-on-cvss: 1
#          min-cvss-for-issue: 1
